name: '[Assistente] Mercado Livre - Web'
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Installing Angular CLI
        run: yarn global add @angular/cli

      - name: Installing dependencies
        run: yarn --frozen-lockfile

      - name: Build a SPA Angular Application
        run: yarn build

      - name: Upload build-app-artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-app-artifact
          path: dist/assistente-mercado-livre

  deploy:
    needs: build
    name: Angular Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Download build-app-artifact
        uses: actions/download-artifact@v2
        with:
          name: build-app-artifact
          path: ./build

      - name: Fire Deployment
        run: heroku container:push -app assistente-mercado-livre-web ./build
